version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - ${BACK}
  ui:
    build: ./ui
    image: ${USERNAME}/ui:2.0
    ports:
      - 9292:9292/tcp
    networks:
      - ${FRONT}
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - ${BACK}
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - ${BACK}
      - ${FRONT}

volumes:
  post_db:
  comment_db:
networks:
  reddit:
  back_net:
  front_net:
